# Generated by Django 5.1.7 on 2025-03-09 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('specjalizacja', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=12, null=True)),
                ('adres', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wizyty', models.DateTimeField()),
                ('status', models.SmallIntegerField(choices=[(0, 'zaplanowana'), (1, 'odwołana'), (2, 'zakończona')])),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestracja.lekarz')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rejestracja.pacjent')),
            ],
        ),
    ]
