# Generated by Django 5.1.7 on 2025-03-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestracja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizyta',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'zaplanowana'), (1, 'odwołana'), (2, 'zakończona')], default=0),
        ),
    ]
