# Generated by Django 5.1.7 on 2025-03-17 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestracja', '0002_alter_wizyta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lekarz',
            name='godzina_do',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lekarz',
            name='godzina_od',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
    ]
